name: rust tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: never
  NO_COLOR: 1

jobs:
  test:
    if: contains(fromJson('["aws-samples", "jplock"]'), github.repository_owner)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: '1.95'
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Format
        run: cargo fmt --all -- --check --verbose
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: No-panic verification
        run: ./scripts/check_no_panic.sh
      - name: Run tests
        run: cargo test --verbose
